version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
  sidekiq:
    build: .
    volumes:
      - .:/kwartracker-api
    links:
      - db
      - redis
    command: bundle exec sidekiq
    environment:
      REDIS_URL: "redis://redis:6379/12"
  redis:
    image: redis
  web:
    env_file: .env
    environment:
      RAILS_ENV: development
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/kwartracker-api
    environment:
      REDIS_URL: "redis://redis:6379/12"
